comment:
  on-update: recreate

  snippets:
    - id: submodules-changed
      files:
        - 'tgstation'
      body: |
       Hey, listen! You appear to be passing through a commit change on the tgstation submodule.
       Please do not PR any changes to the submodule! Please attempt to remove the change.
       You may peruse https://github.com/tgstation/map_depot/blob/main/README.md#submodules for more information.
